# Generated by Django 3.2.18 on 2023-03-23 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.CharField(max_length=40, verbose_name='Дата занятия'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_materials',
            field=models.TextField(verbose_name='Материалы к занятию'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
    ]
