# Generated by Django 3.2.18 on 2023-04-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='content_main',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default=1, max_length=32, verbose_name='ссылка на видео'),
            preserve_default=False,
        ),
    ]
