# Generated by Django 3.2.18 on 2023-03-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_main', models.CharField(max_length=120)),
                ('content_main', models.TextField()),
                ('title_about', models.CharField(max_length=120)),
                ('content_about', models.TextField()),
            ],
        ),
    ]
